---

- name: upgrade/update apt based hosts
  hosts: all

  tasks:
  - include_tasks: overlayfs-off-tasks.yml
  - include_tasks: apt-upgrade-tasks.yml
 # - include: cleanup-tasks.yml need to sort out where to putr vars
  - include_tasks: overlayfs-on-tasks.yml
    tags: always
