---

# Deal with some things that have been overlooked during previous setup/config
# * timezone
# * passwordless sudo
# * locale and LANG settings

- name: miscellaneous cleanup
  hosts: all

  vars:
    config_system_locale: 'en_US.UTF-8'
    config_system_language: 'en_US.UTF-8'


  tasks:
    - include: cleanup-tasks.yml