---

# commands to execute after the first boot for a Raspberry Pi

- name: Configure a Pi on initial boot
  hosts: all
  tasks:

  - name: collect IP settings
    shell: "ip addr"
    register: ip_settings

  - name: show IP settings
    debug: var=ip_settings.stdout_lines

  - name: update/upgrade
    apt:
      cache_valid_time: 3600
      install_recommends: no
      upgrade: yes
      autoclean: yes
    register: update_upgrade

  - name: show update/upgrade results
    debug: var=update_upgrade.stdout_lines

  - name: install commonly used applications
    apt:
      pkg:
      - vim
      - mosquitto-clients
      - tree
      - lsof
      - mbuffer
      - s-tui
      - stress-ng
    register: SW_install

  - name: show S/W install results
    debug: var=SW_install.stdout_lines

  - name: Check if passwordless sudo enabled
    stat:
      path: /etc/sudoers.d/010_pi-nopasswd
    register: passwordless_enabled

  - name: prevent passwordless sudo
    become: yes
    shell: "mv /etc/sudoers.d/010_pi-nopasswd /etc/sudoers.d/010_pi-nopasswd~"
    when: passwordless_enabled.stat.exists

  - name: reboot following updates
    reboot:
