---
# Install and provision an SD card on localhost (before first boot.)
- name: Provision SD card before initial boot
  hosts: localhost
  connection: local 
  tasks:

  - name: "just execute a ls -lrt command"
    shell: "ls -lrt {{sd_dev}}p?" # wildcard pattern for e.g. {{/dev/mmcblk0}}p0 
    register: "output"

  - name: list partitions
    debug: var=output.stdout_lines

  - name: build list of mounted partitions
    shell: "df 2>/dev/null|grep {{sd_dev}}|awk '{print $1}'"
    register: "partitions"

  - name: list mounted partitions
    debug: var=partitions.stdout_lines

  - name: unmount partitions
    shell: "umount {{ item }}"
    with_items: "{{ partitions.stdout_lines }}"

  - name: copy OS image
    become: yes
    shell: "xzcat {{os_image}} > {{sd_dev}}"
    when: os_image is defined

  - name: create boot partition mount point
    become: yes
    file:
      path: /mnt/boot 
      state: directory

  - name: mount new boot partition
    become: yes
    shell: "mount {{sd_dev}}p1 /mnt/boot"

  - name: copy three files to boot partition
    become: yes
    copy:
      src: /home/hbarta/.secrets/{{item}}
      dest: /mnt/boot/{{item}}
    with_items:
     - ssh
     - wpa_supplicant.conf
     - userconf.txt
  
  - name: unmount new boot partition
    become: yes
    shell: "umount {{sd_dev}}p1"

#  - name: list unmounted partitions
#    debug: var=unmounted.stdout_lines

#  - name: Unmount a mounted volume
#    command: umount /dev/mmcblk0p1
